//! `garnet doc <file>` — extract `///` doc comments from a Garnet
//! source file and emit a markdown summary beside it.
//!
//! ## Scope
//!
//! The parser does not retain `///` lines on AST nodes (lexer drops
//! all comments as trivia). To extract doc comments without
//! reshaping the parser, this command does a separate source-text
//! scan: for each top-level item the parser surfaces, walk the
//! source backwards from the item's start span over consecutive
//! `///` lines and collect them as that item's doc text.
//!
//! Output is a single markdown file at `<file>.doc.md`. The Mini-Spec
//! v1.0 §16.4 doc-comment syntax is supported as written:
//!
//! ```text
//! ## A short summary of the function.
//! ##
//! ## # Examples
//! ##
//! ## ```garnet
//! ## let result = fibonacci(10)
//! ## ```
//! ```
//!
//! HTML rendering, cross-references, search index, and a `--workspace`
//! mode that resolves imports across files are all v0.5.x roadmap
//! items (likely landing alongside the LSP in `garnet-lsp`).

use crate::cmd::describe_item;
use crate::read_file;
use garnet_parser::ast::Annotation;
use std::path::PathBuf;
use std::process::ExitCode;

pub fn run(args: &[String]) -> ExitCode {
    let mut to_stdout = false;
    let mut out_path: Option<String> = None;
    let mut file: Option<String> = None;
    let mut i = 0;
    while i < args.len() {
        match args[i].as_str() {
            "--stdout" => {
                to_stdout = true;
                i += 1;
            }
            "--out" => {
                if i + 1 >= args.len() {
                    eprintln!("--out requires a path argument");
                    return ExitCode::from(2);
                }
                out_path = Some(args[i + 1].clone());
                i += 2;
            }
            "--help" | "-h" => {
                print_help();
                return ExitCode::SUCCESS;
            }
            other if !other.starts_with("--") => {
                file = Some(args[i].clone());
                i += 1;
            }
            other => {
                eprintln!("unknown doc flag: {other}");
                return ExitCode::from(2);
            }
        }
    }

    let Some(file) = file else {
        print_help();
        return ExitCode::from(2);
    };
    let path = PathBuf::from(&file);
    let src = match read_file(&path) {
        Ok(s) => s,
        Err(e) => {
            eprintln!("{e}");
            return ExitCode::from(1);
        }
    };

    let module = match garnet_parser::parse_source(&src) {
        Ok(m) => m,
        Err(e) => {
            let report = miette::Report::new(e).with_source_code(src);
            eprintln!("{report:?}");
            return ExitCode::from(1);
        }
    };

    let rendered = render_module_md(&path, &src, &module);

    if to_stdout {
        print!("{rendered}");
        return ExitCode::SUCCESS;
    }

    let out = out_path.map(PathBuf::from).unwrap_or_else(|| {
        path.with_extension(format!(
            "{}.doc.md",
            path.extension()
                .map(|e| e.to_string_lossy().into_owned())
                .unwrap_or_default()
        ))
    });

    if let Err(e) = std::fs::write(&out, &rendered) {
        eprintln!("garnet doc: failed to write {}: {e}", out.display());
        return ExitCode::from(1);
    }
    println!("documented {} -> {}", path.display(), out.display());
    ExitCode::SUCCESS
}

fn render_module_md(
    path: &std::path::Path,
    src: &str,
    module: &garnet_parser::ast::Module,
) -> String {
    let mut out = String::new();
    out.push_str(&format!("# {}\n\n", path.display()));
    out.push_str(&format!(
        "_Generated by `garnet doc`. {} top-level items._\n\n",
        module.items.len()
    ));

    for item in &module.items {
        let span = item_span(item);
        let docs = extract_doc_comments_before(src, span.start);
        out.push_str(&format!("## {}\n\n", describe_item(item)));
        if docs.is_empty() {
            out.push_str("_no doc comment_\n\n");
        } else {
            out.push_str(&docs);
            out.push_str("\n\n");
        }
    }
    out
}

/// Return the source span of an item's leading token. Used to locate
/// where to scan backwards for `///` lines. Shared with `garnet doctest`
/// (`cmd::doctest`), which reuses this doc-extraction foundation.
pub(crate) fn item_span(item: &garnet_parser::ast::Item) -> garnet_parser::token::Span {
    use garnet_parser::ast::Item;
    match item {
        Item::Fn(f) => f
            .annotations
            .iter()
            .filter_map(annotation_span)
            .min_by_key(|span| span.start)
            .unwrap_or(f.span),
        Item::Struct(s) => s.span,
        Item::Enum(e) => e.span,
        Item::Trait(t) => t.span,
        Item::Protocol(p) => p.span,
        Item::Impl(i) => i.span,
        Item::Actor(a) => a.span,
        Item::Memory(m) => m.span,
        Item::Module(m) => m.span,
        Item::Use(u) => u.span,
        Item::Const(c) => c.span,
        Item::Let(l) => l.span,
    }
}

fn annotation_span(annotation: &Annotation) -> Option<garnet_parser::token::Span> {
    match annotation {
        Annotation::MaxDepth(_, span)
        | Annotation::FanOut(_, span)
        | Annotation::RequireMetadata(span)
        | Annotation::Safe(span)
        | Annotation::Dynamic(span)
        | Annotation::Caps(_, span)
        | Annotation::Mailbox(_, span)
        | Annotation::Bounded(_, span)
        | Annotation::NonSendable(span) => Some(*span),
    }
}

/// Walk backwards from `byte_offset` over consecutive `///` lines (any
/// amount of leading whitespace). Returns a single block of markdown:
/// each `///` stripped, lines preserved in order. Empty if the item
/// has no preceding doc block. Shared with `garnet doctest`.
pub(crate) fn extract_doc_comments_before(src: &str, byte_offset: usize) -> String {
    // Clamp into bounds so a synthetic span past EOF cannot panic.
    let cutoff = byte_offset.min(src.len());
    let head = &src[..cutoff];

    // Walk backwards line-by-line. Stop as soon as we hit a line that
    // is not a `///` line and not blank inside a contiguous block.
    let mut collected: Vec<&str> = Vec::new();
    for line in head.lines().rev() {
        let trimmed = line.trim_start();
        if let Some(rest) = trimmed.strip_prefix("///") {
            // Strip leading single space conventionally written after `///`.
            let body = rest.strip_prefix(' ').unwrap_or(rest);
            collected.push(body);
        } else if trimmed.is_empty() && !collected.is_empty() {
            // Blank line *inside* a doc block (rare but allowed) — stop.
            break;
        } else {
            // First non-doc, non-blank line walking up — boundary.
            break;
        }
    }

    if collected.is_empty() {
        return String::new();
    }
    collected.reverse();
    collected.join("\n")
}

fn print_help() {
    println!("usage: garnet doc [--stdout | --out <path>] <file.garnet>");
    println!();
    println!("  Extract `///` doc comments from a Garnet source file and emit a");
    println!("  markdown summary, one section per top-level item.");
    println!();
    println!("  Modes:");
    println!("    (default)        write to <file>.doc.md beside the source");
    println!("    --out <path>     write to a specific output path");
    println!("    --stdout         print to stdout; do not write a file");
    println!();
    println!("  Scope: markdown extraction only. There is no HTML rendering, no");
    println!("  cross-referencing and no `--workspace` resolution.");
}

#[cfg(test)]
mod tests {
    use super::extract_doc_comments_before;

    #[test]
    fn extracts_simple_block() {
        let src = "/// First line.\n/// Second line.\ndef main() {}\n";
        let offset = src.find("def").unwrap();
        assert_eq!(
            extract_doc_comments_before(src, offset),
            "First line.\nSecond line."
        );
    }

    #[test]
    fn returns_empty_when_no_doc() {
        let src = "// regular comment\ndef main() {}\n";
        let offset = src.find("def").unwrap();
        assert_eq!(extract_doc_comments_before(src, offset), "");
    }

    #[test]
    fn stops_at_non_doc_line() {
        let src = "// regular comment\n/// real doc\ndef main() {}\n";
        let offset = src.find("def").unwrap();
        assert_eq!(extract_doc_comments_before(src, offset), "real doc");
    }

    #[test]
    fn strips_one_space_after_slashes() {
        let src = "///doc one\n/// doc two\ndef main() {}\n";
        let offset = src.find("def").unwrap();
        assert_eq!(extract_doc_comments_before(src, offset), "doc one\ndoc two");
    }

    #[test]
    fn handles_offset_past_eof() {
        let src = "/// doc\ndef main() {}\n";
        // Offset deliberately past the end — must not panic.
        assert_eq!(extract_doc_comments_before(src, src.len() + 1000), "");
    }
}
